[Dependencies] - Update .github/actions/dotnet-publish/action.yml to match the template repo

diff --git a/.github/actions/dotnet-publish/action.yml b/.github/actions/dotnet-publish/action.yml
--- a/.github/actions/dotnet-publish/action.yml
+++ b/.github/actions/dotnet-publish/action.yml
@@ -29,12 +29,26 @@ runs:
   - name: "Dotnet: Pack For Octopus"
     working-directory: ${{github.workspace}}/src/${{inputs.OCTOPUS_DEPLOY_PACKAGE}}
     shell: bash
-    run: dotnet publish -warnaserror --configuration:Release -r:${{inputs.PLATFORM}} --self-contained -p:NoWarn=NETSDK1179 -p:PublishSingleFile=true -p:PublishAot=false -p:PublishReadyToRun=False -p:PublishReadyToRunShowWarnings=True -p:PublishTrimmed=False -p:DisableSwagger=False -p:TreatWarningsAsErrors=True "-p:Version=${{inputs.BUILD_VERSION}}" -p:IncludeNativeLibrariesForSelfExtract=false -p:SolutionDir=..\\ --output ../server-dist/${{inputs.PLATFORM} -nodeReuse:False
+    run: dotnet publish -warnaserror --configuration:Release -r:${{inputs.PLATFORM}} --self-contained -p:NoWarn=NETSDK1179 -p:PublishSingleFile=true -p:PublishAot=false -p:PublishReadyToRun=False -p:PublishReadyToRunShowWarnings=True -p:PublishTrimmed=False -p:DisableSwagger=False -p:TreatWarningsAsErrors=True "-p:Version=${{inputs.BUILD_VERSION}}" -p:IncludeNativeLibrariesForSelfExtract=false -p:SolutionDir=..\\ --output ../server-dist/${{inputs.PLATFORM}} -nodeReuse:False
     env:
       ReleaseNotes: ${{inputs.RELEASE_NOTES}}
       DOTNET_ROOT: "${{github.workspace}}/.dotnet"
       DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet"
-      DOTNET_MULTILEVEL_LOOKUP: false
+      DOTNET_MULTILEVEL_LOOKUP: "false"
+      DOTNET_NOLOGO: "true"
+      DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
+      DOTNET_ReadyToRun: "0"
+      DOTNET_TC_QuickJitForLoops: "1"
+      DOTNET_TieredPGO: "1"
+
+  - name: "Dotnet: Stop build server post publish"
+    working-directory: ${{github.workspace}}/src
+    shell: bash
+    run: dotnet build-server shutdown && echo "Build server closed" || echo "Failed to shutdown build server"
+    env:
+      DOTNET_ROOT: "${{github.workspace}}/.dotnet"
+      DOTNET_INSTALL_DIR: "${{github.workspace}}/.dotnet"
+      DOTNET_MULTILEVEL_LOOKUP: "false"
       DOTNET_NOLOGO: "true"
       DOTNET_PRINT_TELEMETRY_MESSAGE: "false"
       DOTNET_ReadyToRun: "0"
