[Actions] Updated .github/actions/npm/action.yml

diff --git a/.github/actions/npm/action.yml b/.github/actions/npm/action.yml
--- a/.github/actions/npm/action.yml
+++ b/.github/actions/npm/action.yml
@@ -120,8 +120,16 @@ runs:
     shell: bash
     run: rm -rf "${{github.workspace}}/node-modules"
 
+  - name: "Npm: Clear node modules"
+    id: build_context
+    shell: bash
+    run: |
+      [ -f ${{github.workspace}}/package-lock.json ] && echo "WORK_DIR=${{github.workspace}}" >> "$GITHUB_OUTPUT" && exit 0
+      [ -f ${{github.workspace}}/src/package-lock.json ] && echo "WORK_DIR=${{github.workspace}}/src" >> "$GITHUB_OUTPUT" && exit 0
+      echo "Error: no package-lock.json" && exit 1
+
   - name: "NPM: Force registry before restore"
-    working-directory: ${{github.workspace}}/src
+    working-directory: ${{steps.build_context.outputs.WORK_DIR}}
     shell: bash
     run: |
       sed -i "s|https://registry.npmjs.org/|${{inputs.NPM_REGISTRY}}|g" package-lock.json
@@ -129,7 +137,7 @@ runs:
       sed -i "s|https://npm.local:5555/|${{inputs.NPM_REGISTRY}}|g" package-lock.json
 
   - name: "NPM: Install dependencies"
-    working-directory: ${{github.workspace}}/src
+    working-directory: ${{steps.build_context.outputs.WORK_DIR}}
     shell: bash
     run: |
       npm install \
@@ -147,7 +155,7 @@ runs:
   #   run: npm run test
 
   - name: "NPM: Build"
-    working-directory: ${{github.workspace}}/src
+    working-directory: ${{steps.build_context.outputs.WORK_DIR
     shell: bash
     run: npm run build
 
