[Actions] Updated .github/workflows/build-and-publish-release.yml

diff --git a/.github/workflows/build-and-publish-release.yml b/.github/workflows/build-and-publish-release.yml
--- a/.github/workflows/build-and-publish-release.yml
+++ b/.github/workflows/build-and-publish-release.yml
@@ -33,8 +33,16 @@ jobs:
       RELEASE_BAGET_CACHE: ''
 
     steps:
+      - name: "Check Required Secrets"
+        shell: bash
+        run: |
+          if [ -z "${{secrets.SOURCE_PUSH_TOKEN}}" ]; then
+            echo "::error::SOURCE_PUSH_TOKEN is required but not set"
+            exit 1
+          fi
+
       - name: "Initialise Workspace"
-        if: startsWith(runner.name, 'buildagent-')
+        if: runner.environment == 'self-hosted'
         shell: bash
         run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"
 
@@ -42,11 +50,11 @@ jobs:
         shell: bash
         run: |
           {
-          echo "ACTIVE_RUNNER_NAME=${{runner.name}}"
-          echo "ACTIVE_HOSTNAME=$HOSTNAME"
-          echo "ACTIVE_USER=$USER"
-          echo "TEMP=${{runner.temp}}"
-          echo "TMP=${{runner.temp}}"
+            echo "ACTIVE_RUNNER_NAME=${{runner.name}}"
+            echo "ACTIVE_HOSTNAME=$HOSTNAME"
+            echo "ACTIVE_USER=$USER"
+            echo "TEMP=${{runner.temp}}"
+            echo "TMP=${{runner.temp}}"
           } >> "$GITHUB_ENV"
 
       - name: "Checkout Source"
@@ -61,7 +69,7 @@ jobs:
         shell: bash
         run: echo "USE_NUGET_CACHE=false" >> "$GITHUB_ENV"
 
-      - if: startsWith(runner.name, 'buildagent-') != true
+      - if: runner.environment != 'self-hosted'
         name: "Ensure on github agents nuget cache is disabled"
         shell: bash
         run: echo "USE_NUGET_CACHE=false" >> "$GITHUB_ENV"
