[Actions] Updated .github/workflows/create-prs-for-stale-branches.yml

diff --git a/.github/workflows/create-prs-for-stale-branches.yml b/.github/workflows/create-prs-for-stale-branches.yml
--- a/.github/workflows/create-prs-for-stale-branches.yml
+++ b/.github/workflows/create-prs-for-stale-branches.yml
@@ -216,6 +216,19 @@ jobs:
         with:
           path: ./.github/PULL_REQUEST_TEMPLATE.md
 
+      - name: "Check Required Secrets"
+        if: |-
+          steps.detection.outputs.defaultbranch != matrix.branch
+          && steps.find-pull-request.outputs.number == ''
+          && steps.aheadbehind.outputs.ahead != 0
+          && steps.aheadbehind.outputs.dayssinceupdate > 7
+        shell: bash
+        run: |
+          if [ -z "${{secrets.PR_CREATE_TOKEN}}" ]; then
+            echo "::error::PR_CREATE_TOKEN is required but not set"
+            exit 1
+          fi
+
       - name: "Create PR"
         if: |-
           steps.detection.outputs.defaultbranch != matrix.branch
@@ -225,7 +238,7 @@ jobs:
         id: open-pr
         uses: ./.github/actions/create-pull-request
         with:
-          github-token: ${{github.token}}
+          github-token: ${{secrets.PR_CREATE_TOKEN}}
           source-branch: ${{matrix.branch}}
           destination-branch: ${{steps.detection.outputs.defaultbranch}}
           assignee: ${{github.actor}}
