[Actions] Updated .github/workflows/dotnet-version.yml

diff --git a/.github/workflows/dotnet-version.yml b/.github/workflows/dotnet-version.yml
--- a/.github/workflows/dotnet-version.yml
+++ b/.github/workflows/dotnet-version.yml
@@ -23,8 +23,16 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: "Check Required Secrets"
+        shell: bash
+        run: |
+          if [ -z "${{secrets.SOURCE_PUSH_TOKEN}}" ]; then
+            echo "::error::SOURCE_PUSH_TOKEN is required but not set"
+            exit 1
+          fi
+
       - name: "Initialise Workspace"
-        if: startsWith(runner.name, 'buildagent-')
+        if: runner.environment == 'self-hosted'
         shell: bash
         run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"
 
@@ -32,9 +40,9 @@ jobs:
         shell: bash
         run: |
           {
-          echo "ACTIVE_RUNNER_NAME=${{runner.name}}"
-          echo "ACTIVE_HOSTNAME=$HOSTNAME"
-          echo "ACTIVE_USER=$USER"
+            echo "ACTIVE_RUNNER_NAME=${{runner.name}}"
+            echo "ACTIVE_HOSTNAME=$HOSTNAME"
+            echo "ACTIVE_USER=$USER"
           } >> "$GITHUB_ENV"
 
       - name: "Checkout Source"
@@ -46,7 +54,7 @@ jobs:
           token: ${{secrets.SOURCE_PUSH_TOKEN}}
 
       - name: "Install Build tools"
-        if: startsWith(runner.name, 'buildagent-')
+        if: runner.environment == 'self-hosted'
         uses: ./.github/actions/build-tools
         with:
           GITHUB_TOKEN: ${{secrets.SOURCE_PUSH_TOKEN}}
@@ -58,7 +66,7 @@ jobs:
           NUGET_ADDITIONAL_RESTORE_FEED_PRERELEASE: ${{vars.NUGET_ADDITIONAL_RESTORE_FEED_PRERELEASE}}
 
       - name: "Install Build tools"
-        if: startsWith(runner.name, 'buildagent-') != true
+        if: runner.environment != 'self-hosted'
         uses: ./.github/actions/build-tools
         with:
           GITHUB_TOKEN: ${{secrets.SOURCE_PUSH_TOKEN}}
@@ -71,6 +79,7 @@ jobs:
 
       - name: "Get latest installed dotnet version"
         id: latest-dotnet-version
+        shell: bash
         run: |
           echo "Versions installed:"
           dotnet --list-sdks | cut -f 1 -d " " | grep "^[0-9]*\.[0-9]*\.[0-9]*$" | sort --version-sort
@@ -78,12 +87,14 @@ jobs:
           echo "LATEST_RELEASE_VERSION=$(dotnet --list-sdks | cut -f 1 -d " " | grep "^[0-9]*\.[0-9]*\.[0-9]*$" | sort --version-sort | tail -1)" >> "$GITHUB_OUTPUT"
 
       - name: "Display latest installed dotnet version"
+        shell: bash
         run: |
           echo "Latest installed dotnet version: ${{steps.latest-dotnet-version.outputs.LATEST_RELEASE_VERSION}}"
           echo "Requested dotnet version: ${{env.DOTNET_VERSION}}"
 
       - name: "Check if Latest is newer than the current defined"
         id: upgrade_check
+        shell: bash
         run: |
           VER=$(echo "${{env.DOTNET_VERSION}} ${{steps.latest-dotnet-version.outputs.LATEST_RELEASE_VERSION}}" | tr ' ' '\n' | uniq | sort --version-sort | tail -1)
           echo "Latest Version: $VER"
